"""Independent FastMCP exercise; all scientific oracles were generated by direct R."""
import asyncio
import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys
import pytest
from fastmcp import Client
from fastmcp.exceptions import ToolError

ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT/'reports/verification/quickstart'
sys.path.insert(0,str(ROOT/'src'))
from tools.quickstart import quickstart_mcp

def sha(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()

def invoke(tool,args):
    async def run():
        async with Client(quickstart_mcp) as client:
            return (await client.call_tool(tool,args)).data
    return asyncio.run(run())

def artifact(result,kind):
    return Path(next(a['path'] for a in result['artifacts'] if a['kind']==kind))

@pytest.fixture(scope='session',autouse=True)
def setup():
    os.environ.update(P2A_PROJECT_ROOT=str(ROOT),P2A_RSCRIPT='/usr/local/bin/Rscript',P2A_R_PROJECT=str(ROOT/'r-runtime'))
    immutable={str(p):sha(p) for p in (ROOT/'notebooks/quickstart/reference').glob('*') if p.is_file()}
    source=json.loads((ROOT/'notebooks/quickstart/source_hashes_before.json').read_text())
    assert all(sha(ROOT/'repo/occJSDM'/p)==h for p,h in source.items())
    (OUT/'immutable_before.json').write_text(json.dumps(immutable,indent=2)+'\n')
    yield
    assert all(sha(p)==h for p,h in immutable.items())
    assert all(sha(ROOT/'repo/occJSDM'/p)==h for p,h in source.items())

@pytest.fixture(scope='session')
def constant_fit():
    import uuid,shutil
    from tools.runtime import fresh_output,write_json_atomic
    out=fresh_output('verifier_constant_fixture');fp=out/'fit.rds'
    shutil.copyfile(ROOT/'notebooks/quickstart/data/diagnostic_constant_species_fit.rds',fp)
    fid='fit_'+uuid.uuid4().hex;mp=out/'manifest.json'
    write_json_atomic(mp,dict(status='complete',fit_id=fid,fit_path=str(fp),fit_sha256=sha(fp),model='binary',effective_settings={},qualifications=['Verifier boundary fixture: modified saved native chains; never interpret scientifically.']))
    write_json_atomic(ROOT/'artifacts/registry'/(fid+'.json'),dict(manifest_path=str(mp),manifest_sha256=sha(mp)))
    return fid,fp,mp

@pytest.fixture(scope='session')
def specs():
    return json.loads((OUT/'independent_inputs.json').read_text())

@pytest.fixture(scope='session')
def exercised(specs):
    before={c['data_path']:sha(c['data_path']) for c in specs.values()}
    results={}
    for name,c in specs.items():
        opts=c['options']; args=dict(data_path=c['data_path'],occCovariates=opts['occCovariates'],collCovariates=opts['collCovariates'])
        valid=invoke('validate_data',args)
        assert valid['eligible'] is True
        if 'error' in c:
            old=set((ROOT/'artifacts/registry').glob('*.json'))
            with pytest.raises(ToolError,match=c['error']):
                invoke('fit_model',dict(data_path=c['data_path'],options=opts,seed=c['seed']))
            assert set((ROOT/'artifacts/registry').glob('*.json'))==old
            results[name]={'validate_data':valid,'native_error':c['error']}
            continue
        fit=invoke('fit_model',dict(data_path=c['data_path'],options=opts,seed=c['seed']))
        diag=invoke('diagnostics',dict(fit_id=fit['fit_id'],max_rows=2))
        summary=invoke('summarise_fit',dict(fit_id=fit['fit_id'],max_rows=1))
        results[name]=dict(validate_data=valid,fit_model=fit,diagnostics=diag,summarise_fit=summary)
    assert all(sha(p)==s for p,s in before.items())
    (OUT/'mcp_exercised_results.json').write_text(json.dumps(results,indent=2,allow_nan=False)+'\n')
    return results

@pytest.fixture(scope='session')
def numerical_audit(exercised):
    saved=json.loads((ROOT/'notebooks/quickstart/reference/native_execution_results.json').read_text())['cases']
    selected={}
    manifests=[json.loads(p.read_text()) for p in (ROOT/'artifacts/calls').glob('fit_model-*/manifest.json')]
    manifests=[m for m in manifests if m.get('status')=='complete' and all(k in m for k in ('requested_settings','seed','input_path','input_sha256','fit_path','fit_sha256'))]
    for name,c in saved.items():
        if name.startswith('boundary_') and name!='boundary_two_stage_NA_OTU':continue
        if c['fit']['status']!='ok':continue
        oc=c['occCovariates'];cc=c['collCovariates']
        oc=oc if isinstance(oc,list) else [oc];cc=cc if isinstance(cc,list) else [cc]
        expected=dict(occCovariates=oc,collCovariates=cc,threshold=1,listParams={'n_factors':2},MCMCparams=c['settings'])
        candidates=[m for m in manifests if m['input_path']==str(ROOT/f'notebooks/quickstart/data/{name}_data.rds') and m['requested_settings']==expected and m['seed']==c['seed']]
        assert candidates,name
        m=candidates[-1]
        assert sha(m['fit_path'])==m['fit_sha256'] and sha(m['input_path'])==m['input_sha256']
        selected[name]=m
    (OUT/'saved_manifest_selection.json').write_text(json.dumps(selected,indent=2)+'\n')
    run=subprocess.run(['/usr/local/bin/Rscript','--vanilla',str(ROOT/'tests/code/quickstart/independent_audit.R'),str(ROOT)],capture_output=True,text=True)
    (OUT/'audit.log').write_text(run.stdout+run.stderr)
    assert run.returncode==0,run.stdout+run.stderr
    return json.loads((OUT/'numerical_audit.json').read_text())
