#!/usr/bin/env Rscript
args <- commandArgs(trailingOnly=TRUE)
root <- normalizePath(args[1]);dest<-args[2]
files <- list.files(file.path(root,c('main-results','operational-k6')),'-result.rds$',full.names=TRUE)
zfiles <- list.files(file.path(root,'known-z'),'-result.rds$',full.names=TRUE)
stopifnot(length(files)==230L,length(zfiles)==20L)
status<-c(readRDS(file.path(root,'main-results/job-status.rds')),readRDS(file.path(root,'operational-k6/job-status.rds')));stopifnot(length(status)==230L,all(vapply(status,is.character,logical(1))))
a<-readRDS(file.path(root,'main-results/settings-initial.rds'));b<-readRDS(file.path(root,'main-results/settings.rds'))
stopifnot(identical(a$mcmc,b$mcmc),identical(a$source_revision,b$source_revision),identical(head(a$hashes,-1),head(b$hashes,-1)),identical(unname(tools::md5sum(names(b$hashes))),unname(b$hashes)))
k6<-readRDS(file.path(root,'operational-k6/settings.rds'));stopifnot(identical(b$mcmc,k6$mcmc),identical(b$source_revision,k6$source_revision),identical(head(b$hashes,-1),head(k6$hashes,-1)),identical(unname(tools::md5sum(names(k6$hashes))),unname(k6$hashes)))
records<-lapply(files,readRDS)
manifest<-do.call(rbind,lapply(seq_along(files),function(i){r<-records[[i]];j<-r$job;input<-readRDS(j$input_file);data.frame(key=j$key,scenario=input$scenario$label,replicate=input$replicate,prior=j$prior_name,seed=input$seed,nchain=j$mcmc$nchain,nburn=j$mcmc$nburn,niter=j$mcmc$niter,nthin=j$mcmc$nthin,input_md5=unname(tools::md5sum(j$input_file)),result_md5=unname(tools::md5sum(files[i])),started=as.character(r$started),finished=as.character(r$finished),warnings=length(r$warnings),psi_reconstruction_error=r$reconstruction['psi'],theta_reconstruction_error=r$reconstruction['theta'])}))
stopifnot(all(manifest$nchain==2),all(manifest$nburn==3000),all(manifest$niter==5000),all(manifest$psi_reconstruction_error<1e-10),all(manifest$theta_reconstruction_error<1e-10),length(unique(manifest$key))==230L)
counts<-table(manifest$scenario,manifest$prior);stopifnot(all(counts[counts>0]==10L))
dir.create(dest,recursive=TRUE,showWarnings=FALSE)
copy<-function(from,to=file.path(dest,basename(from))){stopifnot(file.copy(from,to,overwrite=TRUE))}
scripts<-c('run_nonspatial_recheck.R','run_nonspatial_recheck_balanced.R','run_nonspatial_recheck_k6.R','run_known_z_control.R','run_long_convergence_checks.R','summarise_nonspatial_recheck.R','summarise_known_z.R','summarise_collection_contrasts.R','summarise_pcr_comparisons.R','summarise_long_convergence_checks.R','review_detection_ordering_case.R','plot_nonspatial_recheck.R','plot_occupancy_error_explainer.R','review_nonspatial_diagnostics.R','package_nonspatial_recheck.R')
for(p in scripts)copy(file.path(root,p))
dir.create(file.path(dest,'q-audit'),showWarnings=FALSE)
for(p in c('audit_q.R','reproduce_threshold_preprocessing.R','audit_completed_fits.R'))copy(file.path(root,'q-audit',p),file.path(dest,'q-audit',p))
dir.create(file.path(dest,'results'),showWarnings=FALSE)
for(p in list.files(file.path(root,'main-results/summary'),full.names=TRUE))copy(p,file.path(dest,'results',basename(p)))
for(p in list.files(file.path(root,'q-audit'),pattern='[.]csv$',full.names=TRUE))copy(p,file.path(dest,'results',basename(p)))
for(p in c('ordering_summary.csv','ordering_pairs.csv','collection_species.csv','collection_groups.csv','status.csv'))copy(file.path(root,'q-audit/completed-fits',p),file.path(dest,'results',p))
write.csv(manifest,file.path(dest,'results/fit-manifest.csv'),row.names=FALSE)
hashes<-unique(rbind(data.frame(file=names(b$hashes),md5=unname(b$hashes)),data.frame(file=names(k6$hashes),md5=unname(k6$hashes))));hashes$file<-sub(paste0(root,'/'),'',hashes$file,fixed=TRUE);write.csv(hashes,file.path(dest,'results/source-fingerprints.csv'),row.names=FALSE)
writeLines(c(paste('Approved main source:',b$source_revision),'Spatial effects absent from generation and fitting.','230 fits (170 original grid plus 60 operational K6 extension) plus 20 paired exact-occupancy controls.','Each main arm: 10 independently simulated datasets; priors compared on identical data.','Each fit: 2 chains, 3000 burn-in and 5000 retained iterations per chain; no thinning.','One sampler thread per fit; four R workers per batch; the K6 extension overlapped the finishing original batch.','117 main fits completed before restarting the queue with chunk.size=1L.','Original and resumed runners differ only in scheduling; the fitted package, input data, RNG state and MCMC settings are identical.','Pilots: 6 initial collection fits and 28 short grid fits; excluded from final numerical summaries.','Doug specified a maximum of six PCR replicates per primer; sixty K6 fits were added using the original qtest seed scheme. K30 is diagnostic only.', 'No default prior changed. Doug requested errors first and release targets later.','Two selected K3 fits with scored-parameter Rhat above 1.1 were scheduled for 4 chains, 6000 burn-in and 12000 retained iterations per chain, then stopped at user request before completed diagnostic results. Primary-grid summaries remain intact; this sensitivity check is outstanding.', 'Full raw fits, inputs and settings remain in the local investigation folder; compact derived data and executed scripts are committed.','',capture.output(b$session)),file.path(dest,'results/provenance.txt'))
cat('Packaged',nrow(manifest),'main fits and',length(zfiles),'controls in',dest,'\n')
