#!/usr/bin/env Rscript
args<-commandArgs(trailingOnly=TRUE);root<-normalizePath(if(length(args))args[1] else '.')
sdir<-file.path(root,'main-results/summary');g<-read.csv(file.path(sdir,'dataset-groups.csv'));e<-read.csv(file.path(sdir,'parameter-elements.csv'))
stopifnot(length(unique(paste(g$scenario,g$prior,g$replicate)))==230L)
probability_metrics<-c('occupancy','collection_probability','p','q','theta0')
by_metric<-do.call(rbind,lapply(split(g,g$metric),function(x)data.frame(metric=x$metric[1],group_rows=nrow(x),max_rhat=max(x$rhat),min_ess_mean=min(x$ess_mean),max_mcse=max(x$mcse),max_chain_gap=max(x$chain_gap),rows_rhat_above_1_05=sum(x$rhat>1.05),rows_rhat_above_1_1=sum(x$rhat>1.1))))
write.csv(by_metric,file.path(sdir,'mcmc-group-diagnostics.csv'),row.names=FALSE)
write.csv(g[order(-g$rhat),],file.path(sdir,'mcmc-group-ranked.csv'),row.names=FALSE)
write.csv(e[order(-e$rhat),],file.path(sdir,'mcmc-parameter-ranked.csv'),row.names=FALSE)
w<-read.csv(file.path(sdir,'warnings.csv'));w<-w[!is.na(w$warning),]
wt<-as.data.frame(table(w$warning));names(wt)<-c('warning','count');write.csv(wt,file.path(sdir,'warning-counts.csv'),row.names=FALSE)
o<-read.csv(file.path(root,'q-audit/completed-fits/ordering_summary.csv'));stopifnot(nrow(o)==200L)
order_summary<-do.call(rbind,lapply(split(o,interaction(o[c('scenario','prior')],drop=TRUE)),function(x)data.frame(scenario=x$scenario[1],prior=x$prior[1],datasets=nrow(x),mean_draw_share_p_le_q=mean(x$overall_probability_p_le_q),max_pair_share_p_le_q=max(x$maximum_pair_probability_p_le_q),max_chain_pair_share_p_le_q=max(x$maximum_chain_pair_probability_p_le_q),pairs_majority_reversed=sum(x$pairs_majority_reversed),pairs_any_chain_majority_reversed=sum(x$pairs_any_chain_majority_reversed))))
write.csv(order_summary,file.path(sdir,'p-q-ordering-summary.csv'),row.names=FALSE)
options(width=170);print(by_metric,row.names=FALSE,digits=4);print(order_summary,row.names=FALSE,digits=4)
cat(nrow(w),'warnings in',length(unique(w$key)),'fits; no rows discarded.\n')
k<-read.csv(file.path(sdir,'known-w.csv'))
k$a<-ifelse(k$metric=='q',1,ifelse(k$prior=='p32',3,5))
k$b<-ifelse(k$metric=='q',ifelse(k$prior=='q9',9,20),ifelse(k$prior=='p32',2,1))
k$expected_prior_bias<-(k$a-(k$a+k$b)*k$truth)/(k$n+k$a+k$b)
kd<-do.call(rbind,lapply(split(k,interaction(k[c('scenario','prior','replicate','metric')],drop=TRUE)),function(x)data.frame(x[1,c('scenario','prior','replicate','metric')],truth=mean(x$truth),estimate=mean(x$estimate),bias=mean(x$bias),mae=mean(abs(x$bias)),expected_prior_bias=mean(x$expected_prior_bias),mean_observations=mean(x$n))))
ks<-do.call(rbind,lapply(split(kd,interaction(kd[c('scenario','prior','metric')],drop=TRUE)),function(x)data.frame(x[1,c('scenario','prior','metric')],datasets=nrow(x),truth=mean(x$truth),estimate=mean(x$estimate),bias=mean(x$bias),between_dataset_se=sd(x$bias)/sqrt(nrow(x)),mae=mean(x$mae),expected_prior_bias=mean(x$expected_prior_bias),mean_observations=mean(x$mean_observations))))
write.csv(kd,file.path(sdir,'known-collection-state-dataset-results.csv'),row.names=FALSE)
write.csv(ks,file.path(sdir,'known-collection-state-summary.csv'),row.names=FALSE)
