from pathlib import Path
import hashlib,json,shutil,zipfile
root=Path.cwd()
stage=root/'tmp/cloud-transfer-stage/occJSDM-mcp'
files=['src/occJSDM_mcp.py','src/requirements.txt','src/tools/__init__.py','src/tools/runtime.py','src/tools/quickstart.py','src/r_scripts/quickstart.R','r-runtime/activate.R','r-runtime/renv.lock','r-runtime/renv/activate.R','r-runtime/renv/settings.json','r-runtime/restore-runtime.R','r-runtime/source-provenance.json','r-runtime/occJSDM-LICENSE','class/posit-assistant-settings.template.json','class/assistant-instructions.md','class/glossary.md','class/non-ai-workflow.R','r-runtime/renv/cellar/occJSDM/occJSDM_0.1.0.tar.gz']
for rel in files:
    src=root/rel
    assert src.is_file() and not src.is_symlink(),rel
    dst=stage/rel
    dst.parent.mkdir(parents=True,exist_ok=True)
    shutil.copy2(src,dst)
provenance=json.loads((stage/'r-runtime/source-provenance.json').read_text())
assert hashlib.sha256((stage/'r-runtime'/provenance['cellar_path']).read_bytes()).hexdigest()==provenance['cellar_sha256']
usage=(root/'USAGE.md').read_text().split('## Developer reference checks')[0]
usage=usage.replace('The source archive and dependency caches are local build payloads, excluded from Git. A copied source folder alone is not an installed runtime. See `r-runtime/README.md` for the retained source archive, its hash and restoration requirements. The Cloud pilot needs that source payload supplied separately before its restore command; the eventual workshop archive is not yet delivered.','This Cloud pilot ZIP includes the pinned scientific source tarball under `r-runtime/renv/cellar/occJSDM/`. It includes no installed libraries or dependency caches. A copied source folder alone is not an installed runtime. See `r-runtime/README.md` for restoration requirements. Workshop adoption and release remain pending.')
usage=usage.replace('For a controlled model trial, use the prepared student-project export and add only the MCP source, runtime files, retained scientific source payload and reviewed teaching instructions. Exclude `reports/`, `notebooks/`, grading notes, tests and saved answer references from the student project. Copying this full development workspace would expose the comparison answers.','For a controlled model trial, add this pilot package to the student project. The ZIP excludes development reports, notebooks, grading notes, tests and saved answer references. The teaching instructions are drafts awaiting classroom review.')
usage=usage.replace('The source payload must already be at','The included source payload is at')
usage=usage.replace('The compact native drivers are tracked; their generated inputs, saved fits and comparison outputs are ignored.','')
usage=usage.replace('P2A_R_PROJECT="$PWD/r-runtime"', 'P2A_R_PROJECT="$PWD/cloud-r-runtime"')
usage=usage.replace('The ZIP excludes development reports, notebooks, grading notes, tests and saved answer references.', 'The ZIP excludes MCP development reports, notebooks, grading notes, tests and saved answer references. The intact upstream R source tarball retains its original package tests.')
setup='''# Cloud pilot transfer\n\nThis is a transfer package for user-run Posit Cloud testing. Cloud installation and Assistant registration have not yet been verified. The server code has passed independent local verification on macOS. This ZIP contains the pinned scientific source package and no installed Mac libraries.\n\nUpload `occJSDM-cloud-pilot.zip` into the Cloud project root using the Files pane. Posit Cloud may offer to unzip uploaded ZIP files. If it extracts automatically, retain the resulting `occJSDM-mcp` folder and skip manual extraction. Place that folder at `mcp/paper2agent`; do not overwrite an existing directory.\n\nIf the ZIP remains unextracted, run in the Cloud Terminal:\n\n```sh\ncd /cloud/project\nunzip occJSDM-cloud-pilot.zip\nmkdir -p mcp\ntest ! -e mcp/paper2agent && mv occJSDM-mcp mcp/paper2agent\n```\n\nThen install from the verified Python 3.12.11 available in this Cloud project:\n\n```sh\ncd /cloud/project/mcp/paper2agent\npython3 -m venv occJSDM-env\n./occJSDM-env/bin/python -m pip install -r src/requirements.txt\nRscript --vanilla r-runtime/restore-runtime.R "$PWD/cloud-r-runtime"\n```\n\nThe R restore requires internet access, the native compiler/toolchain and enough RAM to compile occJSDM. It uses a new isolated library for the pinned package, so your existing ordinary installation remains separate. Save the installation output. If a step fails, inspect its error before continuing; `cloud-r-runtime` must be new or empty when starting restoration.\n\nAfter restoration succeeds, merge the entry from `class/posit-assistant-settings.template.json` into your project's `.posit/assistant/settings.json`. Preserve existing entries. Trust this project workspace in Assistant, then inspect `/mcp`. The connected server should expose `validate_data`, `fit_model`, `diagnostics` and `summarise_fit`. Assistant adds a client namespace to the tool names. See [Posit's MCP configuration documentation](https://assistant.posit.co/docs/reference/mcp-servers/).\n\nDo not paste an API key into this package. Model credentials stay in Assistant. The user-approved named-model trial cap is US$5. See `USAGE.md` for tool requests, artifacts and scientific limits.\n'''
(stage/'CLOUD-SETUP.md').write_text(setup)
(stage/'USAGE.md').write_text(usage)
(stage/'r-runtime/README.md').write_text('''# Pinned R runtime\n\nThe included source is occJSDM 0.1.0 from Git commit `b7b7001e56cea8e3931b09c917ea0e29e6cef3c6`. Its source tarball SHA-256 is `eb9f9004aec5c2b24e404aa7afd795792d9344083a1a441d1262b2ada57bed05`. `source-provenance.json` records the source archive identity, and `renv.lock` pins the required packages. Original license notices are retained in `occJSDM-LICENSE` and the tarball.\n\nRun `Rscript --vanilla r-runtime/restore-runtime.R "$PWD/cloud-r-runtime"` from the package root to create a new isolated runtime. The target must be new or empty. The script downloads renv 1.2.3, restores pinned dependencies and compiles the included source package. Network access and the platform's R/C++17, BLAS/LAPACK, Fortran and TBB requirements are needed. This ZIP contains no dependency cache or installed library. Do not use `--use-local-binaries` in Posit Cloud.\n\nThe original development validation used macOS arm64, R 4.5.0 and a documented dependency cache with occJSDM rebuilt from source. Only the source archive is portable; Cloud/Linux/R 4.6.1 restoration must be tested separately.\n\nFor local relocation validation only, the restore script also supports `--use-local-binaries` on macOS arm64 R 4.5. This requires externally supplied, previously recorded dependency cellar archives and the renv bootstrap package in the extraction's runtime folder. Those cache files are deliberately excluded from this Cloud package. Any such validation must be reported as cache-assisted, and does not test the Cloud network restore.\n\nEvery server R call explicitly activates the selected absolute `P2A_R_PROJECT` via its top-level `activate.R`. This configures project-owned library/cache/sandbox paths before activating renv. User-library fallback is prohibited. The selected runtime's `restore-verification.json` records its package versions and origins.\n''')
assert not any('—' in p.read_text() for p in stage.rglob('*') if p.is_file() and p.suffix in ('.md',))
archive=root/'dist/occJSDM-cloud-pilot.zip'
with zipfile.ZipFile(archive,'w',compression=zipfile.ZIP_DEFLATED,compresslevel=6) as z:
    for p in sorted(stage.rglob('*')):
        if p.is_file():z.write(p,p.relative_to(stage.parent))
with zipfile.ZipFile(archive) as z:
    assert z.testzip() is None
    assert all(n.startswith('occJSDM-mcp/') and '..' not in Path(n).parts for n in z.namelist())
inventory={str(p.relative_to(stage)):hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted(stage.rglob('*')) if p.is_file()}
report={'status':'assembled_pending_extraction_verification','purpose':'Task 5 Cloud transfer pilot; no workshop adoption or delivery gate completion','archive_path':str(archive),'archive_sha256':hashlib.sha256(archive.read_bytes()).hexdigest(),'archive_bytes':archive.stat().st_size,'files':inventory,'cloud_python_user_report':'3.12.11','cloud_installation':'not_run','workflow_complete':False}
(root/'reports/cloud-transfer/bundle-inventory.json').write_text(json.dumps(report,indent=2)+'\n')
print(json.dumps({k:v for k,v in report.items() if k!='files'},indent=2))
