a <- commandArgs(trailingOnly=TRUE)
Sys.setenv(P2A_R_PROJECT=file.path(a[1],'r-runtime'))
source(file.path(a[1],'r-runtime','activate.R'))
d <- readRDS(file.path(a[1],'notebooks/quickstart/data/binary_data.rds'))
save <- function(x,name)saveRDS(x,file.path(a[2],paste0(name,'.rds')))
z <- d;rownames(z$OTU) <- paste0('row',seq_len(nrow(z$info)));save(z,'default_info_otu_rows')
z <- d; rownames(z$info) <- rownames(z$OTU) <- paste0('row',seq_len(nrow(z$info)));save(z,'aligned_rows')
z <- d;rownames(z$info) <- paste0('row',seq_len(nrow(z$info)));rownames(z$OTU) <- rev(rownames(z$info));save(z,'misaligned_rows')
save('malformed object','malformed')
z <- d;colnames(z$OTU) <- NULL;save(z,'missing_species')
z <- d;storage.mode(z$OTU) <- 'character';save(z,'nonnumeric_otu')
z <- d;z$OTU[1,1] <- -1;save(z,'negative_reads')
z <- d;z$OTU[1,1] <- NaN;save(z,'nan_reads')
z <- d;z$OTU[1,1] <- 0.5;save(z,'continuous')
z <- d;z$info$X_psi.EnvCov.1 <- 2;save(z,'constant_covariate')

z <- d;z$traitsMatrix <- z$traits;z$traits <- NULL;save(z,'traits_alias')
