args <- commandArgs(trailingOnly = TRUE)
root <- normalizePath(args[[1]], mustWork = TRUE)
project <- file.path(root, "r-runtime")
ip <- installed.packages()
required <- c("ggplot2", "dplyr", "tidyr", "stringr", "ggcorrplot", "Rcpp", "ggtern", "ggforce", "rlang", "coda", "purrr", "tibble", "ggrepel", "FastGP", "RcppParallel", "RcppArmadillo", "jsonlite", "digest", "renv")
deps <- tools::package_dependencies(required, db = ip, which = c("Depends", "Imports", "LinkingTo"), recursive = TRUE)
needed <- unique(c(required, unlist(deps)))
needed <- setdiff(needed, "R")
stopifnot(all(needed %in% rownames(ip)))
needed <- needed[is.na(ip[needed, "Priority"]) | ip[needed, "Priority"] != "base"]
origins <- data.frame(package = needed, version = ip[needed,"Version"], origin = file.path(ip[needed,"LibPath"], needed), stringsAsFactors = FALSE)
boot <- file.path(project, "bootstrap-library")
stopifnot(file.copy(file.path(ip["renv", "LibPath"], "renv"), boot, recursive = TRUE))
Sys.setenv(RENV_PATHS_CACHE = file.path(project,"cache"), RENV_PATHS_LIBRARY = file.path(project,"library"), RENV_PATHS_SANDBOX = file.path(project,"sandbox"), RENV_CONFIG_CACHE_ENABLED = "FALSE")
.libPaths(c(boot, .Library))
options(repos = c(CRAN = "https://cloud.r-project.org"))
renv::init(project = project, bare = TRUE, force = TRUE, restart = FALSE)
renv::settings$external.libraries(character(), project = project)
renv::settings$use.cache(FALSE, project = project)
renv::settings$snapshot.type("all", project = project)
lib <- renv::paths$library(project = project)
dir.create(lib, recursive = TRUE, showWarnings = FALSE)
for (p in needed) {
  target <- file.path(lib,p)
  if (dir.exists(target)) unlink(target, recursive = TRUE)
  stopifnot(file.copy(file.path(ip[p,"LibPath"],p),lib,recursive = TRUE))
}
origins$destination <- file.path(lib, origins$package)
origins$method <- "documented installed-package copy; not clean lockfile restore"
write.csv(origins, file.path(root,"reports","environment-r-dependency-origins.csv"), row.names = FALSE)
writeLines(lib,file.path(project,"library-path.txt"))
cat("LIBRARY=",lib,"\n",sep="")
