args <- commandArgs(trailingOnly=TRUE)
root <- normalizePath(args[[1]],mustWork=TRUE)
project <- Sys.getenv("P2A_R_PROJECT", unset=file.path(root,"r-runtime"))
Sys.setenv(P2A_R_PROJECT=project)
source(file.path(project,"activate.R"))
lib <- renv::paths$library(project=project)
library(occJSDM)
library(jsonlite)
library(digest)
packages <- installed.packages(lib.loc=lib)
origins <- lapply(rownames(packages),function(p) list(package=p,version=unname(packageDescription(p)$Version),origin=find.package(p)))
stopifnot(all(vapply(origins,function(p)startsWith(p$origin,project),logical(1))))
lock <- renv::lockfile_read(file.path(project,"renv.lock"))
stopifnot(all(rownames(packages) %in% names(lock$Packages)))
stopifnot(all(vapply(origins,function(p)package_version(p$version) == package_version(lock$Packages[[p$package]]$Version),logical(1))))
stopifnot(identical(lock$Packages$occJSDM$RemoteSha,"b7b7001e56cea8e3931b09c917ea0e29e6cef3c6"))
stopifnot(identical(lock$Packages$occJSDM$Source,"Local"))
expected <- c("runOccJSDM","returnConvergenceDiagnostics","returnLatentPresences","returnOccupancyCovariates")
stopifnot(all(expected %in% getNamespaceExports("occJSDM")))
provenance <- read_json(file.path(project,"source-provenance.json"),simplifyVector=TRUE)
archive <- file.path(project,provenance$cellar_path)
stopifnot(identical(digest(archive,algo="sha256",file=TRUE),provenance$cellar_sha256))
figure <- file.path(root,"reports","environment-device-probe.pdf")
pdf(figure); plot(1:3,1:3); dev.off()
stopifnot(file.info(figure)$size>0)
result <- list(status="passed",r_version=R.version.string,r_arch=R.version$arch,rscript="/usr/local/bin/Rscript",project=project,library=lib,lib_paths=.libPaths(),loaded_namespace_origins=lapply(loadedNamespaces(),function(p) list(package=p,origin=find.package(p))),packages=origins,lock_packages=length(lock$Packages),source_commit=lock$Packages$occJSDM$RemoteSha,source_archive_sha256=provenance$git_archive_sha256,cellar_sha256=provenance$cellar_sha256,device_probe=figure,capabilities=as.list(capabilities()))
write_json(result,file.path(root,"reports","environment-r-verification.json"),auto_unbox=TRUE,pretty=TRUE)
print(.libPaths())
cat("Verified",length(origins),"isolated packages and lock versions\n")
