# Columns evaluated inside ggplot2 aesthetics, dplyr data masks or tidyselect.
# Each name and its source functions were reviewed after dead-code cleanup;
# see dev/maintenance/post-beta-maintenance-20261007/data-masked-columns.csv.
# Undefined symbols in retained experimental helpers are intentionally excluded.
utils::globalVariables(c(
  "2.5%",
  "97.5%",
  "Biotic",
  "Env",
  "Max",
  "Min",
  "Output",
  "Primer",
  "Sample",
  "Site",
  "Spatial",
  "Species",
  "chain",
  "high",
  "iter",
  "label",
  "label1",
  "label2",
  "low",
  "lower",
  "mean_lower",
  "med",
  "name",
  "p1",
  "p2",
  "primer_group",
  "primer_parity",
  "q1",
  "q2",
  "r",
  "rownum",
  "sample_group",
  "sample_parity",
  "shade_level",
  "site_color_idx",
  "site_group",
  "species",
  "upper",
  "value",
  "x",
  "y"
))
