# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Seed the package's C++ random number generators
#'
#' Sets the seed for the package's serial C++ sampling stream.
#' Called by \code{runOccJSDM()} with a draw from R's RNG, which is what makes
#' \code{set.seed()} control the sampler. Not intended to be called directly.
#'
#' @param seed a non-negative integer.
#' @keywords internal
setOccJSDMSeed <- function(seed) {
    invisible(.Call(`_occJSDM_setOccJSDMSeed`, seed))
}

sample_z_cpp_parallel <- function(w, psi, theta, theta0, M, sumM) {
    .Call(`_occJSDM_sample_z_cpp_parallel`, w, psi, theta, theta0, M, sumM)
}

sample_w_cim_cipp_parallel <- function(y, y_NA, theta, theta0, p, q, M, K, sumL, sumM, sumK, P, primerId, maxL, z) {
    .Call(`_occJSDM_sample_w_cim_cipp_parallel`, y, y_NA, theta, theta0, p, q, M, K, sumL, sumM, sumK, P, primerId, maxL, z)
}

sample_betatheta_cpp <- function(w, z, beta_theta, idx_z, X_theta, b_betatheta, B_betatheta) {
    .Call(`_occJSDM_sample_betatheta_cpp`, w, z, beta_theta, idx_z, X_theta, b_betatheta, B_betatheta)
}

sample_betatheta_cpp_parallel <- function(w, z, beta_theta, idx_z, X_theta, b_betatheta, B_betatheta) {
    .Call(`_occJSDM_sample_betatheta_cpp_parallel`, w, z, beta_theta, idx_z, X_theta, b_betatheta, B_betatheta)
}

sample_pq_cpp_parallel <- function(c_imk, y_NA, w, idx_p_k, idx_w_k, maxP, a_p, b_p, a_q, b_q) {
    .Call(`_occJSDM_sample_pq_cpp_parallel`, c_imk, y_NA, w, idx_p_k, idx_w_k, maxP, a_p, b_p, a_q, b_q)
}

computeModelLoglikJSDM_cpp <- function(z, eta, model, tau = NULL) {
    .Call(`_occJSDM_computeModelLoglikJSDM_cpp`, z, eta, model, tau)
}

computeModelLoglikFirstStage_cpp <- function(w, z, theta, theta0, idx_z_w) {
    .Call(`_occJSDM_computeModelLoglikFirstStage_cpp`, w, z, theta, theta0, idx_z_w)
}

computeModelLoglikSecondStage_cpp <- function(y, w, p, q, idx_w_k, idx_p_k) {
    .Call(`_occJSDM_computeModelLoglikSecondStage_cpp`, y, w, p, q, idx_w_k, idx_p_k)
}

rinvgamma_cpp <- function(a, b) {
    .Call(`_occJSDM_rinvgamma_cpp`, a, b)
}

K2 <- function(x1, x2, a, l) {
    .Call(`_occJSDM_K2`, x1, x2, a, l)
}

samplePGvariables_parallel <- function(Xbeta) {
    .Call(`_occJSDM_samplePGvariables_parallel`, Xbeta)
}

computeNewOutputs <- function(X, B0_output, B_output, Ks_all, Bs_output, L_output, sigmah_output, idx_ls_output, conflevels, useEnvCov, useSpatial, useBiotic, model, verbose) {
    .Call(`_occJSDM_computeNewOutputs`, X, B0_output, B_output, Ks_all, Bs_output, L_output, sigmah_output, idx_ls_output, conflevels, useEnvCov, useSpatial, useBiotic, model, verbose)
}

sampleBuniv <- function(X, B, b, y, sigma) {
    .Call(`_occJSDM_sampleBuniv`, X, B, b, y, sigma)
}

sample_U_cpp <- function(k, L, XB, XsBs, Omega, sigma_h, model) {
    .Call(`_occJSDM_sample_U_cpp`, k, L, XB, XsBs, Omega, sigma_h, model)
}

KsBproduct <- function(Ks, B, X_s_centers) {
    .Call(`_occJSDM_KsBproduct`, Ks, B, X_s_centers)
}

XtOmegaX_SoR <- function(X, X_centers, Omega, X_s_index, X_s_sor) {
    .Call(`_occJSDM_XtOmegaX_SoR`, X, X_centers, Omega, X_s_index, X_s_sor)
}

sampleB_SoR <- function(X, invB, b, k, Omega, X_s_index, Ks, X_centers) {
    .Call(`_occJSDM_sampleB_SoR`, X, invB, b, k, Omega, X_s_index, Ks, X_centers)
}

spatEffectMeanCpp <- function(Bs_output, Ks, Xs_centers) {
    .Call(`_occJSDM_spatEffectMeanCpp`, Bs_output, Ks, Xs_centers)
}

sample_BBsL_cpp <- function(k, X, Tr, U, G, A, C, sigma_b, Gs, As, Cs, sigma_bs, Ks, Xs_centers, Omega, model, sigma_b0 = 1.0) {
    .Call(`_occJSDM_sample_BBsL_cpp`, k, X, Tr, U, G, A, C, sigma_b, Gs, As, Cs, sigma_bs, Ks, Xs_centers, Omega, model, sigma_b0)
}

sample_BBsL_parallel <- function(k, X, Tr, U, G, A, C, sigma_b, Gs, As, Cs, sigma_bs, Ks, Xs_centers, Omega, model, sigma_b0 = 1.0) {
    .Call(`_occJSDM_sample_BBsL_parallel`, k, X, Tr, U, G, A, C, sigma_b, Gs, As, Cs, sigma_bs, Ks, Xs_centers, Omega, model, sigma_b0)
}

site_loglik_cpp <- function(eta, log_g0, log_g1, loadings, nodes, log_weights) {
    .Call(`_occJSDM_site_loglik_cpp`, eta, log_g0, log_g1, loadings, nodes, log_weights)
}

